// src/styles/tokens.js — design tokens + all inline styles

export const C = {
  bg:            '#0a0b0e',
  surface:       '#111318',
  surfaceAlt:    '#16191f',
  border:        '#1e2229',
  borderBright:  '#2a2f3a',
  red:           '#ff4655',
  orange:        '#ff8c42',
  gold:          '#ffd700',
  green:         '#a8ff78',
  teal:          '#4ecdc4',
  textPrimary:   '#f0ece4',
  textSecondary: '#8a9bb0',
  textMuted:     '#4a5568',
};

export const styles = {
  root:          { minHeight: '100vh', background: C.bg, color: C.textPrimary, fontFamily: "'Montserrat', 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif", position: 'relative', overflowX: 'hidden' },
  header:        { position: 'relative', zIndex: 10, display: 'flex', alignItems: 'center', gap: 24, padding: '16px 32px', borderBottom: `1px solid ${C.border}`, background: `${C.surface}ee`, backdropFilter: 'blur(8px)' },
  logoArea:      { display: 'flex', alignItems: 'center', gap: 12, marginRight: 'auto' },
  logoMark:      { fontSize: 28, color: C.red, lineHeight: 1 },
  logoTitle:     { fontSize: 16, fontWeight: 700, letterSpacing: 4, color: C.textPrimary },
  logoSub:       { fontSize: 10, letterSpacing: 3, color: C.textSecondary, marginTop: 2 },
  nav:           { display: 'flex', gap: 4 },
  navBtn:        { background: 'none', border: `1px solid transparent`, color: C.textSecondary, padding: '6px 16px', fontSize: 11, letterSpacing: 2, cursor: 'pointer', borderRadius: 2, fontFamily: 'inherit', transition: 'all 0.15s' },
  navBtnActive:  { color: C.red, borderColor: C.red, background: `${C.red}11` },
  addMatchBtn:   { background: C.red, border: 'none', color: '#fff', padding: '8px 20px', fontSize: 11, fontWeight: 700, letterSpacing: 2, cursor: 'pointer', borderRadius: 2, fontFamily: 'inherit' },
  filtersPanel:  { position: 'relative', zIndex: 9, background: C.surfaceAlt, borderBottom: `1px solid ${C.border}`, padding: '12px 32px' },
  filtersRow:    { display: 'flex', alignItems: 'flex-end', gap: 16, flexWrap: 'wrap' },
  filterGroup:   { display: 'flex', flexDirection: 'column', gap: 4 },
  filterLabel:   { fontSize: 9, letterSpacing: 2, color: C.textSecondary },
  filterSelect:  { background: C.surface, border: `1px solid ${C.borderBright}`, color: C.textPrimary, padding: '5px 10px', fontSize: 12, fontFamily: 'inherit', borderRadius: 2, cursor: 'pointer' },
  resetBtn:      { background: 'none', border: `1px solid ${C.borderBright}`, color: C.textSecondary, padding: '5px 14px', fontSize: 10, letterSpacing: 2, cursor: 'pointer', fontFamily: 'inherit', borderRadius: 2, alignSelf: 'flex-end' },
  main:          { position: 'relative', zIndex: 1, padding: '24px 32px', maxWidth: 1400, margin: '0 auto' },
  sectionHeader: { display: 'flex', alignItems: 'baseline', gap: 16, marginBottom: 16, marginTop: 8, borderLeft: `3px solid ${C.red}`, paddingLeft: 12 },
  sectionTitle:  { fontSize: 13, fontWeight: 700, letterSpacing: 3 },
  sectionSub:    { fontSize: 11, color: C.textSecondary, letterSpacing: 1 },
  summaryGrid:   { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 12, marginBottom: 32 },
  kpiCard:       { background: C.surface, border: `1px solid ${C.border}`, borderRadius: 4, padding: '20px 20px 16px', position: 'relative', overflow: 'hidden' },
  kpiAccent:     { position: 'absolute', top: 0, left: 0, right: 0, height: 2 },
  kpiValue:      { fontSize: 32, fontWeight: 700, lineHeight: 1, letterSpacing: -1 },
  kpiLabel:      { fontSize: 10, letterSpacing: 3, color: C.textSecondary, marginTop: 6 },
  kpiSub:        { fontSize: 10, color: C.textMuted, marginTop: 3 },
  playersGrid:   { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))', gap: 16 },
  playerCard:    { background: C.surface, border: `1px solid ${C.border}`, borderRadius: 4, padding: 20 },
  playerCardHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 },
  playerName:    { fontSize: 16, fontWeight: 700, letterSpacing: 1 },
  playerAgents:  { fontSize: 11, color: C.textSecondary, marginTop: 3 },
  playerTag:     { fontSize: 9, letterSpacing: 2, border: '1px solid', padding: '3px 8px', borderRadius: 2 },
  playerStatsGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8, marginBottom: 12 },
  statChip:      { background: C.surfaceAlt, border: `1px solid ${C.border}`, borderRadius: 3, padding: '8px 10px', textAlign: 'center' },
  statChipVal:   { fontSize: 16, fontWeight: 700 },
  statChipLabel: { fontSize: 9, letterSpacing: 2, color: C.textSecondary, marginTop: 2 },
  playerMatches: { fontSize: 10, color: C.textMuted, textAlign: 'right' },
  matchList:     { display: 'flex', flexDirection: 'column', gap: 8 },
  matchRow:      { display: 'flex', alignItems: 'center', gap: 20, background: C.surface, border: `1px solid ${C.border}`, borderRadius: 4, padding: '12px 20px 12px 24px', position: 'relative', overflow: 'hidden' },
  matchResult:   { fontSize: 13, fontWeight: 700, letterSpacing: 2, minWidth: 40 },
  matchScore:    { fontSize: 20, fontWeight: 700, minWidth: 60, letterSpacing: 1 },
  matchInfo:     { flex: 1, display: 'flex', flexDirection: 'column', gap: 3 },
  matchOpponent: { fontSize: 14, fontWeight: 600 },
  matchMeta:     { fontSize: 11, color: C.textSecondary, letterSpacing: 1 },
  matchType:     { fontSize: 10, letterSpacing: 2 },
  matchDeleteBtn:{ background: 'none', border: `1px solid ${C.border}`, color: C.textMuted, padding: '4px 10px', fontSize: 10, cursor: 'pointer', borderRadius: 2, fontFamily: 'inherit', letterSpacing: 1 },
  tableWrap:     { overflowX: 'auto', background: C.surface, border: `1px solid ${C.border}`, borderRadius: 4 },
  table:         { width: '100%', borderCollapse: 'collapse' },
  th:            { padding: '10px 16px', textAlign: 'left', fontSize: 10, letterSpacing: 2, color: C.textSecondary, borderBottom: `1px solid ${C.borderBright}`, userSelect: 'none', whiteSpace: 'nowrap' },
  td:            { padding: '10px 16px', fontSize: 13, borderBottom: `1px solid ${C.border}` },
  trEven:        { background: 'transparent' },
  trOdd:         { background: `${C.surfaceAlt}88` },
  empty:         { padding: 32, textAlign: 'center', color: C.textMuted, fontSize: 13, letterSpacing: 2 },
  modalOverlay:  { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.85)', zIndex: 100, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  modal:         { background: C.surface, border: `1px solid ${C.borderBright}`, borderRadius: 4, width: 'min(900px, 95vw)', maxHeight: '90vh', overflow: 'hidden', display: 'flex', flexDirection: 'column' },
  modalHeader:   { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '20px 24px', borderBottom: `1px solid ${C.border}` },
  modalTitle:    { fontSize: 14, fontWeight: 700, letterSpacing: 4 },
  closeBtn:      { background: 'none', border: 'none', color: C.textSecondary, fontSize: 16, cursor: 'pointer' },
  formTabs:      { display: 'flex', borderBottom: `1px solid ${C.border}` },
  formTab:       { flex: 1, background: 'none', border: 'none', borderBottom: '2px solid transparent', color: C.textSecondary, padding: '12px', fontSize: 11, letterSpacing: 2, cursor: 'pointer', fontFamily: 'inherit' },
  formTabActive: { color: C.red, borderBottomColor: C.red },
  formGrid:      { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: 16, padding: 24, overflowY: 'auto' },
  formField:     { display: 'flex', flexDirection: 'column', gap: 6 },
  formLabel:     { fontSize: 9, letterSpacing: 2, color: C.textSecondary },
  formInput:     { background: C.surfaceAlt, border: `1px solid ${C.borderBright}`, color: C.textPrimary, padding: '8px 12px', fontSize: 13, fontFamily: 'inherit', borderRadius: 2, outline: 'none' },
  formPlayersTable: { overflowX: 'auto', overflowY: 'auto', padding: '12px 0', maxHeight: 400 },
  inlineInput:   { background: C.surfaceAlt, border: `1px solid ${C.border}`, color: C.textPrimary, padding: '4px 8px', fontSize: 12, fontFamily: 'inherit', borderRadius: 2, width: 70, outline: 'none' },
  inlineSelect:  { background: C.surfaceAlt, border: `1px solid ${C.border}`, color: C.textPrimary, padding: '4px 6px', fontSize: 12, fontFamily: 'inherit', borderRadius: 2 },
  formNote:      { fontSize: 10, color: C.textMuted, padding: '8px 16px', letterSpacing: 1 },
  formActions:   { display: 'flex', justifyContent: 'flex-end', gap: 12, padding: '16px 24px', borderTop: `1px solid ${C.border}` },
  primaryBtn:    { background: C.red, border: 'none', color: '#fff', padding: '10px 24px', fontSize: 11, fontWeight: 700, letterSpacing: 2, cursor: 'pointer', borderRadius: 2, fontFamily: 'inherit' },
  secondaryBtn:  { background: 'none', border: `1px solid ${C.borderBright}`, color: C.textSecondary, padding: '10px 24px', fontSize: 11, letterSpacing: 2, cursor: 'pointer', borderRadius: 2, fontFamily: 'inherit' },
  // Loading + error
  errorBanner:   { background: `${C.red}18`, border: `1px solid ${C.red}44`, color: C.red, padding: '10px 32px', fontSize: 12, letterSpacing: 1, position: 'relative', zIndex: 8 },
  loadingScreen: { position: 'fixed', inset: 0, background: C.bg, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', zIndex: 50 },
  loadingSpinner:{ fontSize: 40, color: C.red, marginBottom: 16 },
  loadingText:   { fontSize: 12, letterSpacing: 4, color: C.textSecondary },
};
