// Design tokens — CSS var references for inline styles
export const C = {
  bg:           '#0c0e10',
  s1:           '#12151a',
  s2:           '#181c22',
  s3:           '#1f242c',
  border:       'rgba(255,255,255,0.07)',
  border2:      'rgba(255,255,255,0.13)',
  red:          '#e8253c',
  redDim:       'rgba(232,37,60,0.18)',
  amber:        '#f59e0b',
  emerald:      '#10b981',
  sky:          '#38bdf8',
  violet:       '#a78bfa',
  text:         '#e8eaf0',
  text2:        '#8a93a6',
  text3:        '#454e60',
  mono:         "'DM Mono', monospace",
  display:      "'Barlow Condensed', sans-serif",
};

// Legacy compat aliases for components that still use old names
export const styles = {
  // Modal
  modalOverlay: { position:'fixed',inset:0,background:'rgba(0,0,0,0.75)',zIndex:100,display:'flex',alignItems:'flex-start',justifyContent:'center',padding:'40px 16px',backdropFilter:'blur(6px)',overflowY:'auto' },
  modal:        { background:C.s1,border:`1px solid ${C.border2}`,borderRadius:16,width:'min(900px,95vw)',maxHeight:'88vh',overflow:'hidden',display:'flex',flexDirection:'column',boxShadow:'0 40px 80px rgba(0,0,0,0.7)' },
  modalHeader:  { display:'flex',alignItems:'center',justifyContent:'space-between',padding:'20px 26px',borderBottom:`1px solid ${C.border}`,flexShrink:0 },
  modalTitle:   { fontSize:18,fontWeight:800,letterSpacing:'0.08em',textTransform:'uppercase' },
  closeBtn:     { background:C.s3,border:'none',color:C.text2,width:32,height:32,borderRadius:8,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center',fontSize:14 },
  formTabs:     { display:'flex',borderBottom:`1px solid ${C.border}`,flexShrink:0 },
  formTab:      { flex:1,background:'none',border:'none',borderBottom:'2px solid transparent',color:C.text3,padding:14,fontSize:13,fontWeight:700,letterSpacing:'0.1em',cursor:'pointer',fontFamily:"'Barlow Condensed',sans-serif",textTransform:'uppercase' },
  formTabActive:{ color:C.red,borderBottomColor:C.red },
  formGrid:     { display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(190px,1fr))',gap:18,padding:24,overflowY:'auto' },
  formField:    { display:'flex',flexDirection:'column',gap:6 },
  formLabel:    { fontSize:9,fontWeight:700,letterSpacing:'0.15em',color:C.text3,fontFamily:"'DM Mono',monospace",textTransform:'uppercase' },
  formInput:    { background:C.s2,border:`1px solid ${C.border}`,color:C.text,padding:'9px 12px',fontSize:14,fontWeight:600,fontFamily:"'Barlow Condensed',sans-serif",borderRadius:8,outline:'none' },
  formPlayersTable: { overflowX:'auto',overflowY:'auto',padding:'12px 0',maxHeight:420 },
  inlineInput:  { background:C.s2,border:`1px solid ${C.border}`,color:C.text,padding:'5px 8px',fontSize:13,fontFamily:"'DM Mono',monospace",borderRadius:6,width:65,outline:'none' },
  inlineSelect: { background:C.s2,border:`1px solid ${C.border}`,color:C.text,padding:'5px 7px',fontSize:13,fontFamily:"'Barlow Condensed',sans-serif",fontWeight:600,borderRadius:6 },
  formNote:     { fontSize:10,color:C.text3,padding:'8px 24px',fontFamily:"'DM Mono',monospace" },
  formActions:  { display:'flex',justifyContent:'flex-end',gap:10,padding:'16px 24px',borderTop:`1px solid ${C.border}`,flexShrink:0 },
  primaryBtn:   { background:C.red,border:'none',color:'#fff',padding:'10px 24px',fontSize:13,fontWeight:800,letterSpacing:'0.1em',cursor:'pointer',borderRadius:9,fontFamily:"'Barlow Condensed',sans-serif",textTransform:'uppercase',boxShadow:'0 0 16px rgba(232,37,60,0.3)' },
  secondaryBtn: { background:C.s2,border:`1px solid ${C.border}`,color:C.text2,padding:'10px 24px',fontSize:13,fontWeight:700,letterSpacing:'0.1em',cursor:'pointer',borderRadius:9,fontFamily:"'Barlow Condensed',sans-serif",textTransform:'uppercase' },
  // table (used in forms + stats modal)
  table:        { width:'100%',borderCollapse:'collapse' },
  th:           { padding:'10px 14px',textAlign:'left',fontSize:9,fontWeight:700,letterSpacing:'0.15em',color:C.text3,borderBottom:`1px solid ${C.border}`,fontFamily:"'DM Mono',monospace",textTransform:'uppercase',userSelect:'none',whiteSpace:'nowrap' },
  td:           { padding:'10px 14px',fontSize:14,fontWeight:600,borderBottom:`1px solid ${C.border}` },
  trEven:       { background:'transparent' },
  trOdd:        { background:'rgba(255,255,255,0.02)' },
};
